### ISSUE TITLE
Problem with ladybug_tools installation

### ISSUE THREAD

**Issue by nickbelomatis** [Moult/ladybug_tools#1]
I try to install ladybug for blender with no success. Here there are the errors:
Modules Installed (ladybug_tools-master) from 'D:\\blenderAddons\\ladybug_tools-master.zip' into 'C:\\Users\\belom\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\belom\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ladybug_tools-master\__init__.py", line 102, in <module>
    imported_modules = make_node_list()
  File "C:\Users\belom\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ladybug_tools-master\__init__.py", line 98, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ladybug_tools'

**Comment by Moult** [comment]
Hey @nickbelomatis ! I'm flattered by your enthusiasm but this repo is _not_ packaged nor ready for installation yet. There is a little setup process that is required. If you know coding, happy to explain the steps. If not, it's best to wait until the first release.

The place to watch for progress is: https://github.com/nortikin/sverchok/issues/3556 and https://community.osarch.org/discussion/218/ladybug-tools-for-sverchok-and-blender

If you are familiar with ladybug, I'd love for you to be a tester when it is released! I'm sure the first release will still have issues!

**Comment by Moult** [comment]
Also, this repository will be deleted (and migrated to the ladybug-tools owner) when the first package is created, so keep in mind this link will disappear :)

**Comment by Moult** [comment]
@nickbelomatis the first release has been made here: https://community.osarch.org/discussion/comment/2910/#Comment_2910

I will delete this repository at the end of this week :)
